# SPDX-FileCopyrightText: 2026 maninblack
# SPDX-License-Identifier: Apache-2.0

d /var/aos/workdirs/sm/runtimes/systemd-slot-component 0755 root root -
d /var/aos/workdirs/sm/runtimes/systemd-slot-component/slots 0755 root root -
d /var/aos/workdirs/sm/runtimes/systemd-slot-component/state 0700 root root -
d /var/aos/workdirs/sm/runtimes/systemd-slot-component/credentials 0700 root root -
d /var/aos/workdirs/sm/runtimes/systemd-slot-component/configuration 0755 root root -
d /var/aos/workdirs/sm/runtimes/systemd-slot-component/trust 0755 root root -
Z /var/aos/workdirs/sm/runtimes/systemd-slot-component - - - -
