# SPDX-FileCopyrightText: 2026 maninblack
# SPDX-License-Identifier: Apache-2.0
# Post-read configuration for the unchanged warm .28 build graph.
AOS_ROOTFS_IMAGE_VERSION:forcevariable = "6.1.1-maninblack.29"
BB_NO_NETWORK = "1"
BB_FETCH_PREMIRRORONLY = "1"
